spring:
  application:
    name: discovery

server:
  port: 8082

eureka:
  instance:
    hostname: localhost

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#defaultZone: http://localhost:8082/eureka/
      
