server:
  port: 8060

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: hello-service
        uri: lb://hello-service
        #uri: http://localhost:8083
        predicates:
        - Path=/hola/**
        filters:
        - RewritePath=/hola/(?<path>.*), /$\{path}
      - id: caller-service
        uri: lb://caller-service
        #uri: http://localhost:8084
        predicates:
        - Path=/llamar/**
        filters:
        - RewritePath=/llamar/(?<path>.*), /$\{path}
#      - id: department-service
#        uri: lb://department-service
#        predicates:
#        - Path=/department/**
#        filters:
#        - RewritePath=/department/(?<path>.*), /$\{path}
#      - id: organization-service
#        uri: lb://organization-service
#        predicates:
#        - Path=/organization/**
#        filters:
#        - RewritePath=/organization/(?<path>.*), /$\{path}
